name: on-push-main

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/on-push-main.yaml"
      - ".github/workflows/on-version-tagged.yaml"
      - ".gitops/**"
      - "apis/**"
      - "examples/**"
      - "functions/**"
      - "tests/**"
      - "upbound.yaml"

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write # Required for OIDC auth

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.17.0
    with:
      examples: |
        [
          { "example": "examples/observes/minimal.yaml" },
          { "example": "examples/observes/pvc.yaml" },
          { "example": "examples/observes/s3.yaml" }
        ]
      api_path: apis/observes
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.17.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.17.0
    with:
      aws: true
      aws-use-oidc: true
      aws-account-id: "034489662075"
      aws-region: us-east-2
      aws-role-duration-seconds: 7200
      debug-resource-types: |
        [
          "observes.stacks.hops.ops.com.ai"
        ]
      delete-extra-resources: |
        [
          "autoeksclusters.aws.hops.ops.com.ai"
        ]
      timeout-minutes: 44
      cleanup-timeout-minutes: 20
      delete-extra-resources-timeout-minutes: 20

  version-and-tag:
    name: Version and Tag
    needs:
      - validate
      - test
      - e2e
    uses: unbounded-tech/workflow-vnext-tag/.github/workflows/workflow.yaml@v1.21.0
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    with:
      useDeployKey: true
